version: '3.8'

volumes:
  mongo1_data: {}
  mongo2_data: {}
  mongo3_data: {}

services:
  mongo1:
    container_name: mongo1
    image: mongo
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo1
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongo1_data:/data/db:rw

  mongo2:
    container_name: mongo2
    image: mongo
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo2
    ports:
      - "27018:27017"
    restart: unless-stopped
    volumes:
      - mongo2_data:/data/db:rw

  mongo3:
    container_name: mongo3
    image: mongo
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo3
    ports:
      - "27019:27017"
    restart: unless-stopped
    volumes:
      - mongo3_data:/data/db:rw

  express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo1
    depends_on:
      - mongo1
